POST http://localhost:3000/pet-owners/zSorour/posts HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNjNjhjNDg5NGViZjkwZjE5MzVjNWQiLCJ1c2VybmFtZSI6InpTb3JvdXIiLCJpYXQiOjE2NDA3ODk1MzMsImV4cCI6MTY0MDc5MzEzM30.s2O3r5ce4NkrdY6-95lO74bESkcxzPktqu9AMAC-Jzk 

{
    "body":"Have a good day"
}