DELETE http://localhost:3000/pet-owners/zSorour/posts HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNhZTFmOGFlNTkwNzU5M2RkYmE1NWYiLCJ1c2VybmFtZSI6InpTb3JvdXIiLCJpYXQiOjE2NDA3MjM1MTEsImV4cCI6MTY0MDcyNzExMX0.DSCGjJoG6imVixAr0ekMEAR0aD2j3op_NsY1k9GU1II 

{
    "postID": "61cb7cbb5d25a4d1ca80de61"
}