POST http://localhost:5000/pet-owners/zSorour77/pets HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWQwMmVjOWZlMGU0M2Q4NWY5ODM2YTMiLCJ1c2VybmFtZSI6InpTb3JvdXI3NyIsImlhdCI6MTY0MTAzODg0MCwiZXhwIjoxNjQxMDQyNDQwfQ.g2zTbB-x7oT2Z1YvDnvyT4YMce_r7sN-FGTy1iZOdB4

{
    "petName":"Kiko",
    "petType": "Cat",
    "petBreed": "Mau",
    "petAge": "2"
}