POST http://localhost:5000/pet-owners/nour/posts HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNjNzc4MWU2N2YyM2NiYjUwMDNmZmYiLCJ1c2VybmFtZSI6Im5vdXIiLCJpYXQiOjE2NDEwNDAwOTgsImV4cCI6MTY0MTA0MzY5OH0.OUrILQ2y7fzy-MZLm_AFSFUebc2fWQu9zb4SqF-YwJ0 

{
    "body":"Hi there!"
}