GET http://localhost:5000/pet-owners/zSorour/nearby-vets HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNjNjhjNDg5NGViZjkwZjE5MzVjNWQiLCJ1c2VybmFtZSI6InpTb3JvdXIiLCJpYXQiOjE2NDA5NjgxMDIsImV4cCI6MTY0MDk3MTcwMn0.ioxcHGfvhzEFUOJ59xWFsYcfGmN_6AKm_ZLjBjUQ7r8