GET http://localhost:5000/pet-owners/zSorour/nearby-vets HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNjNjhjNDg5NGViZjkwZjE5MzVjNWQiLCJ1c2VybmFtZSI6InpTb3JvdXIiLCJpYXQiOjE2NDEwNDYxMTksImV4cCI6MTY0MTA0OTcxOX0.1MQDzrh2deWlDMiDILOvnAL7AFcn3EfZaJkpBGLTvQM