PATCH http://localhost:5000/pet-owners/nour HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWNjNzc4MWU2N2YyM2NiYjUwMDNmZmYiLCJ1c2VybmFtZSI6Im5vdXIiLCJpYXQiOjE2NDEwMzYxNjksImV4cCI6MTY0MTAzOTc2OX0.Nr2Ov58pTNbkBnY_AltNDTO3MUVJsPche0XqkTZDpG0

{
    "name": "Nourhan",
    "phoneNumber": "01024661195",
    "email": "nourhan123@gmail.com"
}